### ISSUE TITLE
Throwing error on payment page

### ISSUE THREAD

**Issue by Kofacts** [Kendysond/Prestashop-Paystack#3]
On the payments page, i am getting the error.
Unknown error on line 19 in file C:\\xampp\\htdocs\\crystalpines\\modules\\prestapaystack\\backward_compatibility\\Display.php
[2048] Declaration of BWDisplay::setTemplate() should be compatible with FrontControllerCore::setTemplate($template, $params = Array, $locale = NULL)

**Comment by Kendysond** [comment]
Hello @Kofacts 

Apologies for the inconvenience. 

Please what pretashop version are you running? And what's your Xampp PHP version ?

**Comment by Kofacts** [comment]
The error was more of a live server stuff.
Already fixed it though.
